# General variables
_QUIET=true
_DEBUG=false
_LOGGING=true

# set to true for running script under ./scripts directory
_RUN_BACKUP_SYNC=false
_RUN_BACKUP_MYSQL=false
_RUN_BACKUP_POSTGRESQL=false
_RUN_BACKUP_VBOX=false
_RUN_BACKUP_PSONO=false

## backups files options
#_CONFIG_RCLONE=
#RCLONE_EXTRA_OPTIONS=
#RCLONE_BACKUP_REMOTE=   #<rclone-config>

#BACKUP_DIR=(dir1 dir2)
#BACKUP_FILES=()

## PostgreSQL
POSTGRESQL_HOST=
POSTGRESQL_USER=
POSTGRESQL_PASS=
POSTGRESQL_PORT=
POSTGRESQL_DATABASE_IGNORE=(postgres template0 template1)
POSTGRESQL_DATABASE=

# MySQL
MYSQL_HOST=
MYSQL_USER=
MYSQL_PASS=
MYSQL_PORT=
MYSQL_DATABASES_IGNORE=(information_schema performance_schema mysql)
MYSQL_DATABASES=

# keep last backups
# _DEFAULT_KEEP_LAST_BACKUPS_DAILY=7
# _DEFAULT_KEEP_LAST_BACKUPS_WEEKLY=4     # keep last day of the week
# _DEFAULT_KEEP_LAST_BACKUPS_MONTHLY=6    # keep last day of the month
# _DEFAULT_KEEP_LAST_BACKUPS_ANNUALLY=1   # keep last day of the year

# _FILES_KEEP_LAST_BACKUPS_DAILY=${_DEFAULT_KEEP_LAST_BACKUPS_DAILY}
# _FILES_KEEP_LAST_BACKUPS_WEEKLY=${_DEFAULT_KEEP_LAST_BACKUPS_WEEKLY}       # keep last day of the week
# _FILES_KEEP_LAST_BACKUPS_MONTHLY=${_DEFAULT_KEEP_LAST_BACKUPS_MONTHLY}     # keep last day of the month
# _FILES_KEEP_LAST_BACKUPS_ANNUALLY=${_DEFAULT_KEEP_LAST_BACKUPS_ANNUALLY}   # keep last day of the year

# _SYNC_KEEP_LAST_BACKUPS_DAILY=${_DEFAULT_KEEP_LAST_BACKUPS_DAILY}
# _SYNC_KEEP_LAST_BACKUPS_WEEKLY=${_DEFAULT_KEEP_LAST_BACKUPS_WEEKLY}       # keep last day of the week
# _SYNC_KEEP_LAST_BACKUPS_MONTHLY=${_DEFAULT_KEEP_LAST_BACKUPS_MONTHLY}     # keep last day of the month
# _SYNC_KEEP_LAST_BACKUPS_ANNUALLY=${_DEFAULT_KEEP_LAST_BACKUPS_ANNUALLY}   # keep last day of the year

# _POSTGRESQL_KEEP_LAST_BACKUPS_DAILY=${_DEFAULT_KEEP_LAST_BACKUPS_DAILY}
# _POSTGRESQL_KEEP_LAST_BACKUPS_WEEKLY=${_DEFAULT_KEEP_LAST_BACKUPS_WEEKLY}       # keep last day of the week
# _POSTGRESQL_KEEP_LAST_BACKUPS_MONTHLY=${_DEFAULT_KEEP_LAST_BACKUPS_MONTHLY}     # keep last day of the month
# _POSTGRESQL_KEEP_LAST_BACKUPS_ANNUALLY=${_DEFAULT_KEEP_LAST_BACKUPS_ANNUALLY}   # keep last day of the year

# _MYSQL_KEEP_LAST_BACKUPS_DAILY=${_DEFAULT_KEEP_LAST_BACKUPS_DAILY}
# _MYSQL_KEEP_LAST_BACKUPS_WEEKLY=${_DEFAULT_KEEP_LAST_BACKUPS_WEEKLY}       # keep last day of the week
# _MYSQL_KEEP_LAST_BACKUPS_MONTHLY=${_DEFAULT_KEEP_LAST_BACKUPS_MONTHLY}     # keep last day of the month
# _MYSQL_KEEP_LAST_BACKUPS_ANNUALLY=${_DEFAULT_KEEP_LAST_BACKUPS_ANNUALLY}   # keep last day of the year

# _VBOX_KEEP_LAST_BACKUPS_DAILY=${_DEFAULT_KEEP_LAST_BACKUPS_DAILY}
# _VBOX_KEEP_LAST_BACKUPS_WEEKLY=${_DEFAULT_KEEP_LAST_BACKUPS_WEEKLY}       # keep last day of the week
# _VBOX_KEEP_LAST_BACKUPS_MONTHLY=${_DEFAULT_KEEP_LAST_BACKUPS_MONTHLY}     # keep last day of the month
# _VBOX_KEEP_LAST_BACKUPS_ANNUALLY=${_DEFAULT_KEEP_LAST_BACKUPS_ANNUALLY}   # keep last day of the year

# _PSONO_KEEP_LAST_BACKUPS_DAILY=${_DEFAULT_KEEP_LAST_BACKUPS_DAILY}
# _PSONO_KEEP_LAST_BACKUPS_WEEKLY=${_DEFAULT_KEEP_LAST_BACKUPS_WEEKLY}       # keep last day of the week
# _PSONO_KEEP_LAST_BACKUPS_MONTHLY=${_DEFAULT_KEEP_LAST_BACKUPS_MONTHLY}     # keep last day of the month
# _PSONO_KEEP_LAST_BACKUPS_ANNUALLY=${_DEFAULT_KEEP_LAST_BACKUPS_ANNUALLY}   # keep last day of the year

# Send email
EMAIL= #true|false
EMAILADDR=
EMAILSUBJECT="Backup host01"

# Slack notifications
# Defaults keys, title and msg ({"title": "Backups success", "msg": "backups finish at ..."})
SLACK= #true|false
CHANNEL=

# VBox values
TEMPDIR=/local/backups
VBOX_VM=(vbox01 vbox02)
VBOX_PATH="/local/vbox/VirtualBox\ VMs"
WEEK_DAY=6
