# General variables
_QUIET=true
_DEBUG=false
_LOGGING=true

# set to true for running script under ./scripts directory
_RUN_BACKUP_SYNC=false
_RUN_BACKUP_MYSQL=false
_RUN_BACKUP_POSTGRESQL=false
_RUN_BACKUP_VBOX=false
_RUN_BACKUP_PSONO=false

## backups files options
#_CONFIG_RCLONE=
#RCLONE_EXTRA_OPTIONS=
#RCLONE_BACKUP_REMOTE=   #<rclone-config>

#BACKUP_DIR=(dir1 dir2)
#BACKUP_FILES=()

## PostgreSQL
POSTGRESQL_HOST=
POSTGRESQL_USER=
POSTGRESQL_PASS=
POSTGRESQL_PORT=
POSTGRESQL_IGNORE="(template|template1)"
POSTGRESQL_DATABASE=

# MySQL
MYSQL_HOST=
MYSQL_USER=
MYSQL_PASS=
MYSQL_PORT=
MYSQL_DATABASES_IGNORE=(information_schema performance_schema mysql)
MYSQL_DATABASES=

# Keep backups
_DEFAULT_DAYS=15

# Send email
EMAIL= #true|false
EMAILADDR=
EMAILSUBJECT="Backup host01"

# Slack notifications
# Defaults keys, title and msg ({"title": "Backups success", "msg": "backups finish at ..."})
SLACK= #true|false
CHANNEL=



# VBox values
TEMPDIR=/local/backups
VBOX_VM=(vbox01 vbox02)
VBOX_PATH="/local/vbox/VirtualBox\ VMs"
WEEK_DAY=6
